name: Replicate Nightly Cron with Pinned BoTorch

on:

  workflow_dispatch:

jobs:

  tests-and-coverage-minimal:
    name: Tests with pinned BoTorch & minimal dependencies
    uses: ./.github/workflows/reusable_test.yml
    with:
      pinned_botorch: true
      minimal_dependencies: true
    secrets: inherit

  tests-and-coverage-full:
    name: Tests with pinned BoTorch & full dependencies
    uses: ./.github/workflows/reusable_test.yml
    with:
      pinned_botorch: true
      minimal_dependencies: false
    secrets: inherit

  build-tutorials:
    name: Build tutorials with pinned BoTorch
    uses: ./.github/workflows/reusable_tutorials.yml
    with:
      smoke_test: false
      pinned_botorch: true
